Aroma Shop.Mvc/Controllers/MediaController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using Aroma_Shop.Application.Interfaces;
using Aroma_Shop.Application.Utilites;
using Aroma_Shop.Application.ViewModels.Home;
using Aroma_Shop.Application.ViewModels.Product;
using Aroma_Shop.Domain.Models.MediaModels;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Configuration;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Aroma_Shop.Mvc.Controllers
{
    public class MediaController : Controller
    {
        private readonly IMediaService _mediaService;
        private readonly IProductService _productService;
        private readonly IConfiguration _configuration;
        private readonly HttpClient _httpClient;

        public MediaController(IMediaService mediaService, IProductService productService, IConfiguration configuration)
        {
            _mediaService = mediaService;
            _productService = productService;
            _configuration = configuration;
            _httpClient = new HttpClient();
        }

        #region ContactUs

        [HttpGet("/Contact-Us")]
        public IActionResult ContactUs()
        {
            return View();
        }

        [HttpPost("/Contact-Us")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> ContactUs(Message model)
        {
            string recaptchaResponse =
                Request.Form["g-recaptcha-response"];

            var url =
                "https://www.google.com/recaptcha/api/siteverify";

            var response =
                await _httpClient
                    .PostAsync($"{url}?secret={_configuration["reCAPTCHA:SecretKey"]}&response={recaptchaResponse}",
                        new StringContent(""));

            var responseString =
                await response.Content.ReadAsStringAsync();

            dynamic jsonResponse =
                JObject.Parse(responseString);

            if (jsonResponse.success != true)
                ModelState
                    .AddModelError("", "مشکلی در زمان تایید گوگل کپچا رخ داد ، لطفا بعدا تلاش کنید");

            if (ModelState.IsValid)
            {
                var result =
                    await _mediaService
                        .AddMessageAsync(model);

                if (result)
                {
                    ViewData["SuccessMessage"] = "پیام شما با موفقیت ارسال شد.";

                    ModelState.Clear();

                    return View();
                }

                ModelState.AddModelError("", "مشکلی در زمان ارسال پیام رخ داد.");
            }

            return View(model);
        }

        #endregion

        #region AddCommentToProduct

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddCommentToProduct(ProductViewModel model)
        {
            string recaptchaResponse =
                Request.Form["g-recaptcha-response"];

            var url =
                "https://www.google.com/recaptcha/api/siteverify";

            var response =
                await _httpClient
                    .PostAsync($"{url}?secret={_configuration["reCAPTCHA:SecretKey"]}&response={recaptchaResponse}",
                        new StringContent(""));

            var responseString =
                await response.Content.ReadAsStringAsync();

            dynamic jsonResponse =
                JObject.Parse(responseString);

            if (jsonResponse.success != true)
                ModelState
                    .AddModelError("", "مشکلی در زمان تایید گوگل کپچا رخ داد ، لطفا بعدا تلاش کنید");

            if (ModelState.IsValid)
            {
                var productId =
                    Convert.ToInt32(TempData["productId"]);

                var product =
                    await _productService
                        .GetProductWithDetailsAsync(productId);

                product.Comments = 
                    product.Comments;

                model.Product = 
                    product;

                bool result;

                if (model.ParentCommentId == 0)
                    result = await _mediaService
                        .AddCommentToProductAsync(model);
                else
                    result = await _mediaService
                        .AddReplyToProductCommentAsync(model);

                product.Comments =
                    product.Comments
                        .Where(p => p.IsConfirmed && p.ParentComment == null)
                        .ToList();

                if (result)
                {
                    model.CommentDescription = null;

                    model.ParentCommentId = 0;

                    ViewData["SuccessMessage"] = "دیدگاه / پاسخ شما با موفقیت ثبت و بعد از تایید ادمین نمایش داده خواهد شد";

                    ModelState.Clear();

                    return View("/Views/Product/ProductDetails.cshtml", model);
                }

                ModelState.AddModelError("", "مشکلی در زمان ثبت دیدگاه / پاسخ رخ داد.");
            }

            return View("/Views/Product/ProductDetails.cshtml", model);
        }

        #endregion

        #region AddNewsletter

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddNewsletter(string customerEmail)
        {
            if (ModelState.IsValid)
            {
                if (string.IsNullOrWhiteSpace(customerEmail))
                    return Content("EmptyError");

                if (!customerEmail.IsValidEmailAddress())
                    return Content("InvalidEmail");

                if (customerEmail.Length >= 256)
                    return Content("MoreThan256Character");

                var isEmailExistInNewslettersCustomers =
                    await _mediaService
                        .IsEmailExistInNewslettersCustomersAsync(customerEmail);

                if (isEmailExistInNewslettersCustomers)
                    return Content("CustomerEmailExist");

                var result =
                    await _mediaService
                        .AddNewsletterAsync(customerEmail);

                if (result)
                    return Content("Successful");

            }

            return Content("Failed");
        }

        #endregion
    }
}

Aroma Shop.Mvc/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using Aroma_Shop.Application.Interfaces;
using Aroma_Shop.Application.Utilites;
using Aroma_Shop.Application.ViewModels.Product;
using Aroma_Shop.Domain.Models.ProductModels;
using Microsoft.AspNetCore.Authorization;

namespace Aroma_Shop.Mvc.Controllers
{
    public class ProductController : Controller
    {
        private readonly IProductService _productService;
        private readonly IMediaService _mediaService;
        private readonly IAccountService _accountService;

        public ProductController(IProductService productService, IMediaService mediaService, IAccountService accountService)
        {
            _productService = productService;
            _mediaService = mediaService;
            _accountService = accountService;
        }

        #region ShowProducts

        [HttpGet("/Products/")]
        public async Task<IActionResult> Index(int pageNumber = 1, string SortBy = null, string Search = null, IEnumerable<int> SelectedCategories = null, int minimumPrice = 0, int maximumPrice = 0)
        {
            var products =
                await _productService
                    .GetProductsAsync();

            if (!string.IsNullOrEmpty(Search))
            {
                products =
                    products
                    .Where(p => p.ProductName.Contains(Search)
                                || p.Categories
                                    .Any(t => t.CategoryName.Contains(Search)));
            }

            if (SelectedCategories.Any())
            {
                products =
                    products
                        .Where(p => SelectedCategories.Any(t => p.Categories.Any(c => c.CategoryId == t)));
            }

            if (minimumPrice != 0 || maximumPrice != 0)
            {
                products =
                    products
                        .Where(p =>
                        {
                            var minimumPriceForAvailableProductVariations =
                                p.ProductVariations
                                    .Where(t => t.ProductVariationQuantityInStock != 0)
                                    .DefaultIfEmpty(new ProductVariation(){ProductVariationPrice = -1})
                                    .Min(t => t.ProductVariationPrice);

                            var result =
                                p.IsSimpleProduct
                                    ? (p.ProductQuantityInStock != 0 &&
                                       (p.ProductPrice >= minimumPrice &&
                                        p.ProductPrice <= maximumPrice))
                                    : (minimumPriceForAvailableProductVariations >= minimumPrice &&
                                       minimumPriceForAvailableProductVariations <= maximumPrice);

                            return result;
                        });
            }

            ProductsViewModel productsViewModel;

            var categoriesTreeViews =
                await _productService
                    .GetCategoriesTreeViewsAsync();

            ViewData["search"] = Search;
            ViewData["minimumPrice"] = minimumPrice;
            ViewData["maximumPrice"] = maximumPrice;

            if (!products.Any())
            {
                ViewData["isEmpty"] = true;

                productsViewModel = new ProductsViewModel()
                {
                    CategoriesTreeViews = categoriesTreeViews,
                    SelectedCategories = SelectedCategories,
                    SortBy = SortBy
                };

                return View(productsViewModel);
            }

            if (SortBy == "Newest" || string.IsNullOrEmpty(SortBy))
            {
                products =
                    products
                        .OrderByDescending(p =>
                            p.IsSimpleProduct
                                ? Convert.ToBoolean(p.ProductQuantityInStock)
                                : Convert.ToBoolean(
                                    p.ProductVariations.Max(t => t.ProductVariationQuantityInStock)))
                        .ThenByDescending(p => p.RegistrationTime);
            }
            else if (SortBy == "Price-Cheapest")
            {
                products =
                    products
                        .OrderBy(p =>
                            p.IsSimpleProduct
                                ? Convert.ToBoolean(p.ProductQuantityInStock)
                                : Convert.ToBoolean(
                                    p.ProductVariations.Max(t => t.ProductVariationQuantityInStock)))
                        .ThenBy(p =>
                            p.IsSimpleProduct
                                ? p.ProductPrice
                                : ((p.ProductVariations.Any(t => t.ProductVariationQuantityInStock != 0)
                                       ? p.ProductVariations
                                           .Where(t => t.ProductVariationQuantityInStock != 0)
                                           .Min(t => t.ProductVariationPrice)
                                       : p.ProductVariations.Min(t => t.ProductVariationPrice)) +
                                   (p.ProductVariations.Any(t => t.ProductVariationQuantityInStock != 0)
                                       ? p.ProductVariations
                                           .Where(t => t.ProductVariationQuantityInStock != 0)
                                           .Max(t => t.ProductVariationPrice)
                                       : p.ProductVariations.Max(t => t.ProductVariationPrice)) / 2));
            }
            else if (SortBy == "Price-Most-Expensive")
            {
                products =
                    products
                        .OrderByDescending(p =>
                            p.IsSimpleProduct
                                ? Convert.ToBoolean(p.ProductQuantityInStock)
                                : Convert.ToBoolean(
                                    p.ProductVariations.Max(t => t.ProductVariationQuantityInStock)))
                        .ThenByDescending(p =>
                            p.IsSimpleProduct
                                ? p.ProductPrice
                                : ((p.ProductVariations.Any(t => t.ProductVariationQuantityInStock != 0)
                                       ? p.ProductVariations
                                           .Where(t => t.ProductVariationQuantityInStock != 0)
                                           .Min(t => t.ProductVariationPrice)
                                       : p.ProductVariations.Min(t => t.ProductVariationPrice)) +
                                   (p.ProductVariations.Any(t => t.ProductVariationQuantityInStock != 0)
                                       ? p.ProductVariations
                                           .Where(t => t.ProductVariationQuantityInStock != 0)
                                           .Max(t => t.ProductVariationPrice)
                                       : p.ProductVariations.Max(t => t.ProductVariationPrice)) / 2));
            }
            else if (SortBy == "Popularity")
            {
                products =
                    products
                        .OrderByDescending(p =>
                            p.IsSimpleProduct
                                ? Convert.ToBoolean(p.ProductQuantityInStock)
                                : Convert.ToBoolean(
                                    p.ProductVariations.Max(t => t.ProductVariationQuantityInStock)))
                        .ThenByDescending(p => p.ProductHits);
            }

            var page =
                new Paging<Product>(products, 12, pageNumber);

            if (pageNumber < page.FirstPage || pageNumber > page.LastPage)
                return NotFound();

            var productsPage =
                page.QueryResult;

            ViewData["pageNumber"] = pageNumber;
            ViewData["firstPage"] = page.FirstPage;
            ViewData["lastPage"] = page.LastPage;
            ViewData["prevPage"] = page.PreviousPage;
            ViewData["nextPage"] = page.NextPage;
            ViewData["isEmpty"] = false;

            productsViewModel = new ProductsViewModel()
            {
                Products = productsPage,
                CategoriesTreeViews = categoriesTreeViews,
                SelectedCategories = SelectedCategories,
                SortBy = SortBy
            };

            return View(productsViewModel);
        }

        #endregion

        #region ProductDetails

        [HttpGet("/Products/{productId}")]
        public async Task<IActionResult> ProductDetails(int productId)
        {
            var product =
                await _productService
                    .GetProductWithDetailsAsync(productId);

            if (product == null)
                return NotFound();

            await _productService
                .AddHitsToProductAsync(product);

            product.Comments =
                product
                    .Comments
                .Where(p => p.IsConfirmed && p.ParentComment == null).ToList();

            var model = new ProductViewModel()
            {
                Product = product,
            };

            return View(model);
        }

        #endregion

        #region ShoppingCart

        [Authorize]
        [HttpGet("/Shopping-Cart")]
        public async Task<IActionResult> ShoppingCart()
        {
            var loggedUserOpenOrder =
                await _productService
                    .GetLoggedUserOpenOrderAsync();

            return View(loggedUserOpenOrder);
        }

        #endregion

        #region AddProductToCart

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]

Aroma Shop.Mvc/Areas/Admin/Views/Shared/PartialPaging.cshtml
@model string
<nav class="mt-2 mb-5">
    <ul class="pagination justify-content-center">
        <li class="page-item @(ViewData["pageNumber"].ToString()==ViewData["firstPage"].ToString()?"disabled":"")">
            <a class="page-link" asp-action="@Model" asp-route-pageNumber="@ViewData["firstPage"]" asp-route-search="@ViewData["search"]">ابتدا</a>
        </li>
        @for (int i = Convert.ToInt32(ViewData["firstPage"]); i <= Convert.ToInt32(ViewData["lastPage"]); i++)
        {
            <li class="page-item @(ViewData["pageNumber"].ToString()==i.ToString()?"active":"")"><a class="page-link" asp-action="@Model" asp-route-pageNumber="@i" asp-route-search="@ViewData["search"]">@i</a></li>
        }
        <li class="page-item @(ViewData["pageNumber"].ToString()==ViewData["lastPage"].ToString()?"disabled":"")">
            <a class="page-link" asp-action="@Model" asp-route-pageNumber="@ViewData["lastPage"]" asp-route-search="@ViewData["search"]">انتها</a>
        </li>
    </ul>
</nav>

Aroma Shop.Mvc/Areas/Admin/Views/Shared/_AdminLayout.cshtml
@using Aroma_Shop.Application.Interfaces

@inject IAccountService AccountService
@inject IMediaService MediaService
@inject IProductService ProductService

<!DOCTYPE html>
<html lang="fa">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>@ViewData["Title"] - پیشخوان</title>
    <link rel="icon" href="~/img/Fevicon.png" type="image/gif" sizes="16x16">
    <link rel="stylesheet" href="~/vendors/bootstrap/bootstrap-rtl.min.css">
    <link rel="stylesheet" href="~/css/admin/dashboard.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha512-SfTiTlX6kk+qitfevl/7LibUOeJWlt9rbyDn92a1DqWOw9vWG2MFoays0sgObmWazO5BQPiFucnnEAjpAB+/Sw==" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css">
    <link href="~/vendors/tags/tags.min.css" rel="stylesheet" />
    @await RenderSectionAsync("Styles", required: false)
</head>
<body class="rtl">


    <!--================ Start Header Menu Area =================-->
    <nav class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
        <a class="navbar-brand col-md-3 col-lg-2 mr-2 px-3" asp-area="" asp-controller="Home" asp-action="Index">فروشگاه آروما</a>
        <button class="navbar-toggler position-absolute d-md-none collapsed" type="button" data-toggle="collapse" data-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        @{
            var loggedUser =
                await AccountService.GetLoggedUserAsync();

            var loggedUserRole =
                await AccountService
                    .GetUserRoleAsync(loggedUser);
        }
        <span class="badge badge-primary mr-auto ml-2 p-2 dashbord-welcome-badge">@loggedUser.UserName خوش آمدید</span>
        <ul class="navbar-nav px-3">
            <li class="nav-item text-nowrap">
                <form asp-area="" asp-controller="Account" asp-action="LogOut">
                    <a id="logout-a-submit" class="nav-link text-light">خروج</a>
                </form>
            </li>
        </ul>
    </nav>
    <!--================ End Header Menu Area =================-->

    <div class="container-fluid">
        <div class="row">
            <!--================ Start Right Menu Area =================-->
            <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
                <div class="sidebar-sticky pt-3">
                    <ul class="nav flex-column">
                        <li class="nav-item">
                            <a class="nav-link active" aria-current="page" asp-controller="Home" asp-action="Index">
                                <i class="bi bi-house-door"></i>
                                پیشخوان
                            </a>
                        </li>
                        <li class="nav-item ">
                            @{
                                var unSeenOrdersCount =
                                    await ProductService.GetUnSeenOrdersCountAsync();

                                var isThereAnyUnSeenOrder =
                                    unSeenOrdersCount != 0;
                            }
                            <a class="nav-link dropdown-btn products-dashbord-menu">
                                <i class="bi bi-file-earmark"></i>
                                سفارشات
                                @if (isThereAnyUnSeenOrder)
                                {<span class="badge badge-danger">@unSeenOrdersCount</span>}
                            </a>
                            <div class="dropdown-container">
                                <a class="dropdown-item" asp-controller="Order" asp-action="Index">
                                    سفارشات
                                    @if (isThereAnyUnSeenOrder)
                                    {<span class="badge badge-danger">@unSeenOrdersCount</span>}
                                </a>
                                <a class="dropdown-item" asp-controller="Order" asp-action="Discounts">تخفیف ها</a>
                            </div>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link dropdown-btn products-dashbord-menu">
                                <i class="bi bi-files"></i>
                                صفحه ها
                            </a>
                            <div class="dropdown-container">
                                <a class="dropdown-item" asp-controller="Page" asp-action="Index">همه صفحه ها</a>
                                <a class="dropdown-item" asp-controller="Page" asp-action="CreatePage">ساخت صفحه</a>
                            </div>
                        </li>
                        <li class="nav-item ">
                            <a class="nav-link dropdown-btn products-dashbord-menu">
                                <i class="bi bi-cart"></i>
                                محصولات
                            </a>
                            <div class="dropdown-container">
                                <a class="dropdown-item" asp-controller="Product" asp-action="Index">همه محصولات</a>
                                <a class="dropdown-item" asp-controller="Product" asp-action="AddProduct">افزودن محصول</a>
                                <a class="dropdown-item" asp-controller="Product" asp-action="Categories">دسته بندی ها</a>
                            </div>
                        </li>
                        @if (loggedUserRole != "Writer")
                        {
                            <li class="nav-item ">
                                <a class="nav-link dropdown-btn products-dashbord-menu">
                                    <i class="bi bi-people"></i>
                                    کاربران
                                </a>
                                <div class="dropdown-container">
                                    <a class="dropdown-item" asp-controller="User" asp-action="Index">همه کاربران</a>
                                    <a class="dropdown-item" asp-controller="User" asp-action="CreateUser">افزودن کاربر</a>
                                </div>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Media" asp-action="Messages">
                                <i class="bi bi-envelope"></i>
                                صندوق پیام ها @if (await (MediaService.GetUnreadMessagesCountAsync()) != 0)
                                {<span class="badge badge-danger">@await MediaService.GetUnreadMessagesCountAsync()</span>}
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Media" asp-action="Comments">
                                <i class="fa fa-comments-o" aria-hidden="true"></i>
                                دیدگاه ها @if (await (MediaService.GetUnreadCommentsCountAsync()) != 0)
                                {<span class="badge badge-danger">@await MediaService.GetUnreadCommentsCountAsync()</span>}
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link dropdown-btn products-dashbord-menu">
                                <i class="bi bi-images"></i>
                                بنر ها
                            </a>
                            <div class="dropdown-container">
                                <a class="dropdown-item" asp-controller="Media" asp-action="Banners">همه بنر ها</a>
                                <a class="dropdown-item" asp-controller="Media" asp-action="AddBanner">افزودن بنر</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link dropdown-btn products-dashbord-menu">
                                <i class="bi bi-envelope-open"></i>
                                خبرنامه
                            </a>
                            <div class="dropdown-container">
                                <a class="dropdown-item" asp-controller="Media" asp-action="Newsletters">کاربران خبرنامه</a>
                                <a class="dropdown-item" asp-controller="Media" asp-action="AddNewsletter">افزودن کاربر خبرنامه</a>
                            </div>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link dropdown-btn products-dashbord-menu">
                                <i class="bi bi-bar-chart-line"></i>
                                گزارشات
                            </a>
                            <div class="dropdown-container">
                                <a class="dropdown-item" asp-controller="Report" asp-action="Visitors">بازدید ها</a>
                            </div>
                        </li>
                    </ul>
                </div>
            </nav>
            <!--================ End Right Menu Area =================-->

            <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-md-4">
                @RenderBody()
            </main>
        </div>
    </div>

    <!--================ Start Js Libraries Area  =================-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.3.1/js/bootstrap.bundle.min.js" integrity="sha512-TqmAh0/sSbwSuVBODEagAoiUIeGRo8u95a41zykGfq5iPkO9oie8IKCgx7yAr1bfiBjZeuapjLgMdp9UMpCVYQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>    <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js"></script>
    <script src="~/js/site.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
    <script src="~/js/admin/dashboard.js"></script>
    <!--================ End Js Libraries Area  =================-->
</body>
</html>